### ISSUE TITLE
Actual room temperature circuit 2

### ISSUE THREAD

**Issue by icefluffy** [johnaherninfotrack/homeassistant_custom_siemensozw672#1]
I can't seem to acces 

**8770 | Room temperature actual value 2 | 24.5 | °C**

as it is a layer deeper than what this implementation scans.

It seems to be a layer deeper at [1 RVS21.831F/127] > [Diagnostics consumer] > [Heating/Cooling circuit 2]

Would it be possible to dig a layer deeper by adapting code?

![OZW672second Thermostat](https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/assets/8446306/631bc4d6-5d7b-4cb1-a7ff-d3095218cbe0)

**Comment by johnaherninfotrack** [comment]
Interesting! Yes it's possible I think.  What version of OZW672 Firmware are you running?

**Comment by johnaherninfotrack** [comment]
> I can't seem to acces
> 
> **8770 | Room temperature actual value 2 | 24.5 | °C**
> 
> as it is a layer deeper than what this implementation scans.
> 
> It seems to be a layer deeper at [1 RVS21.831F/127] > [Diagnostics consumer] > [Heating/Cooling circuit 2]
> 
> Would it be possible to dig a layer deeper by adapting code?
> 
> ![OZW672second Thermostat](https://user-images.githubusercontent.com/8446306/259491469-631bc4d6-5d7b-4cb1-a7ff-d3095218cbe0.PNG)

Interesting! Yes it's possible I think. What version of OZW672 Firmware are you running?

**Comment by apollon9** [comment]
I confirm @icefluffy's observation, this is also an issue for me with the current ha implementation. 
I run OZW672 v.6.0 as my heating isn't supported by newer revisions.
Example drill-down to "8743 | Vorlauftemperatur Istwert Heizkreis 1" ("heating/cooling circuit 1, actual supply temperature")
Home > 1 RVS21.825E/100 > Diagnostics consumer  > Heating/Cooling circuit 1 > [a dozen values]

1) get sessionID

2) get the top level structure
http://>ip</api/menutree/list.json?SessionId=92a23a6a-83f2-4a03-b6e8-be8b78e486ef
OZW672 has Id=2 and heating controller has Id=4015; this starting Id (4015) is randomly chosen after a factory reset, all Id's down the menu structure (and to measurement values) are different in absolute numbers, but the "distance" remains the same!

3) get the top level inside my heating controller (RVS21.825E/100) which has Id=4015
http://>ip</api/menutree/list.json?SessionId=<..>&Id=4015 -> all top categories inside RVS21.825E/100, among many others (Clock, Status, info etc..) there is "Diagnostics consumer" with Id = 5568

4) List all inside "Diagnostics consumer"
http://>ip</api/menutree/list.json?SessionId=<..>&Id=5568
**Now you get what @icefluffy observes:**
There is a mix of further menu items but also measurement values.
e.g. on the website, "Outside Temperature" is shown on the datapoint window (right) while you can further dig down to "Heating/Cooling circuit 1" in the structure browser (left)

in Json, "Heating/Cooling circuit 1" is the second MenuItem:
{
    "MenuItems": 
        [
        {
            "Id": "5569",
            <omitted for readability>
        },
        {
            "Id": "5572",
                "Text": {
                    "CatId": "2",
                    "GroupId": "4",
                    "Id": "369",
                    "Long": "Heiz-\/Kühlkreis 1",
                    "Short": "Heiz-\/Kühlkreis 1"
                }
        },
[..others..], then
],
"Outside temperature" is the first datapoint item:
	"DatapointItems":
        [
            {
            "Id": "5660",
            "Address": "0x50521",
            "DpSubKey": "0",
            "WriteAccess": "false",
            "Text": {
                   "CatId": "2",
                   "GroupId": "2",
                   "Id": "39",
                   "Long": "Aussentemperatur",
                   "Short": "Aussentemperatur"
            }	

So what we need in this to change the implementation to accept levels that have a mix of "MenuItems" and "DatapointItems" as you can both select Values (->/api/menutree/read_datapoint.json?) as well as dig a level deeper (another /api/menutree/list.json? recursion). Maybe this ends up in changing the way datapoints are selected in the Homeassistant UI. 
Unfortunately, i'm a complete HA newbie (at least, i understand python fairly enough to locate the problem).

**Comment by johnaherninfotrack** [comment]
Thanks - I have implemented recursive submenus in v0.1.4

**Comment by apollon9** [comment]
Excellent!
Works exactly as expected: i can drill down the menu recursively and select one or more branches leading either to further sub-menus or finally the measurement datapoints itself. Everything that was selected shows up in the dashboards then.

Using your implementation is way easier than manually finding the id's through json and pasting them in config.yaml

**Comment by icefluffy** [comment]
> Thanks - I have implemented recursive submenus in v0.1.4 Please let me know if this works. I had to mock up my test data to simulate this as my OZW672 doesn't have this implementation.

Awesome, drilling down one layer deeper did the trick!

THANK YOU SO MUCH!
