### ISSUE TITLE
Celcius en Fahrenheit 

### ISSUE THREAD

**Issue by FritsOV** [johnaherninfotrack/homeassistant_custom_siemensozw672#10]
i got this warning....

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 12:35:45 (9 occurrences)
Last logged: 12:36:38

TEMP_CELSIUS was used from siemens_ozw672, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/issues
TEMP_FAHRENHEIT was used from siemens_ozw672, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/issues
TEMP_KELVIN was used from siemens_ozw672, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.KELVIN instead, please create a bug report at https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/issues

**Comment by johnaherninfotrack** [comment]
Resolved in 0.2.6 - Thank you
