### ISSUE TITLE
request: add unit [kWh] for energy

### ISSUE THREAD

**Issue by apollon9** [johnaherninfotrack/homeassistant_custom_siemensozw672#4]
Feature request: add sensor entity for energy (thermal, electrical) in sensor.py
There:
It must have the "SensorDeviceClass.ENERGY" so that it will show up in HA's energy dashboard.
It must have the "SensorStateClass.total_increasing" to represent its nature as a meter
It must have the 'unit_of_measurement' according to the datapoint description  (e.g. "kWh")

Example datapoint description of energy measurement (OZW JSON):
"Description":
		{
			"Type": "Numeric",
			"Value": "15606.000000",
			"Unit": "kWh",
			"Name": "Eingesetzte Energie",
			"Min": "0.000000",
			"Max": "3500000.000000",
			"Resolution": "1.000000",
			"FieldWitdh": "10",
			"DecimalDigits": "0",
			"HasValid": "false",
			"IsValid": "true"
		},

Minor drawback: Electrical energy and thermal energy will not be distinguishable.

**Comment by johnaherninfotrack** [comment]
This is a great idea.  I can only really simulate this, can't really test.  I'll release it.  Please let me know if it works.

**Comment by apollon9** [comment]
Well... partly. 
Energy sensors now show the correct measurement unit and are recognized by HA's 'energy dashboard'.
Request: resolved.

but..

With the (wallclock) time of the update, I lost some other sensors, common to them is that they all _now_ have 'mdi:numeric' icon, i.e. they are neither °C nor % nor Wh/kWh.
Two of them are the sensors for actual [thermal/electrical] power, which originally reads in kW:
sensor.warmeabgabe:
      state_class: measurement -> [SensorStateClass.MEASUREMENT]
      device_class: power            -> [SensorDeviceClass.POWER]
      unit_of_measurement: "kW"
and now are "unavailable". 
Made a quick fix in sensor.py and just copied/modified "SiemensOzw672EnergyControl" with unit now as ['kW', 'W'] : success, kilowatts are back. You may also want to add it to the routines for new sensor declarations.

The third sensor i lost is a dimensionless number, but rather unimportant to me:
Description	
Type	"Numeric"
Value	"0.000000"
Unit	""
Name	"Leistungszahl"
Min	"0.000000"
Max	"20.000000"
Resolution	"1.000000"
FieldWitdh	"11"
DecimalDigits	"2"
HasValid	"false"
IsValid	"false"

This somehow undergoes all detection mechanisms. Is it that the
```
                 else:
                    continue
```
mechanism now fails? I couldn't figure it out.

Enums work correctly.

bi-state sensors show always "normal" but should display a state [ON | OFF]
Description	
Type	"RadioButton"
Name	"Zustand Verdichter 1"
Buttons	
TextOpt0	"Aus"
TextOpt1	"Ein"
Significance	"1"
IsActive	"false"

hint:
Instead of the is_float detection in sensor.py line 37, float also show by non-zero digits in datapoint description:
DecimalDigits	"2"      -> float
DecimalDigits	"0"     -> int


Everything else works fine, you did a great job for supporting this rather exotic device!

**Comment by johnaherninfotrack** [comment]
I have cleaned up the Config generation on upgrade and added a dedicated Power Sensor.  Let me know if you have any more issues!  Thanks for your help it is much appreciated!
