### ISSUE TITLE
Request: Change domain of numeric datapoints

### ISSUE THREAD

**Issue by michaelf988** [johnaherninfotrack/homeassistant_custom_siemensozw672#5]
Feature request: change entity domain for numeric datapoints to "number"

For statistical purposes it would be great if the entity from numeric datapoints could be categorized as numbers, not as sensors.

Currently all numeric datapoints, which are not writeable are "normal" sensors. So you can't use the built-in historical view as the and the statistics of home assistant can't use the value (see: https://www.home-assistant.io/integrations/statistics/)

Here's a screenshot of a numeric datapoint, which is a "normal" sensor:

![Bildschirmfoto 2023-11-02 22 59 45](https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/assets/83449651/74627b9c-5909-49b5-bb0a-47c1329d1746)

And here's a screenshot of a numeric datapoint, which is a "number" sensor, because it is writeable & percent/temp:

![Bildschirmfoto 2023-11-02 23 09 27](https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/assets/83449651/47d92d42-2709-4ad3-be8a-fbbc1fb65dca)

I would change the definition of the categorization from: 

```
# Number + NOT Writeable + Percent/Temp = Sensor
# Number + Writeable/NOT Writeable + OtherType = Sensor
```

to:

```
# Number + NOT Writeable + Percent/Temp = Number
# Number + Writeable/NOT Writeable + OtherType = Number
```

Example datapoint description of "Brennerstarts Stufe 1" (OZW JSON):
```
{  
  "Description":
    {
    
    
      "Type": "Numeric",
      "Value": "7099.000000",
      "Unit": "",
      "Name": "Brennerstarts Stufe 1",
      "Min": "0.000000",
      "Max": "2147483647.000000",
      "Resolution": "1.000000",
      "FieldWitdh": "10",
      "DecimalDigits": "0",
      "HasValid": "false",
      "IsValid": "true"
    },
    "Result": {
      "Success": "true"
    }
}

```

**Comment by johnaherninfotrack** [comment]
Hi.  This is a good idea.  
The Non-Writeable Number sensors I support today are only Percent or Temp Sensors.  I will look into adding support for non-writeable generic numbers.

<img width="555" alt="image" src="https://github.com/johnaherninfotrack/homeassistant_custom_siemensozw672/assets/12145568/7ab111a9-2612-467e-961e-956ddd84230d">

**Comment by johnaherninfotrack** [comment]
The next release will have this fix in.  Implemented as a Sensor with statistics.

**Comment by johnaherninfotrack** [comment]
Domain changed for numerics
