### ISSUE TITLE
490_flow_temp_min_limitation_heat_circuit_1

### ISSUE THREAD

**Issue by MikaSeppala** [johnaherninfotrack/homeassistant_custom_siemensozw672#7]
Is there way to set value of "490_flow_temp_min_limitation_heat_circuit_1" higher than 50? And "488_flow_temp_max_limitation_heat_circuit_1" lower than 50? That can be done in Siemens control web page.

**Comment by johnaherninfotrack** [comment]
I would need to see some debug.  The integration uses the "min" and "max" values that the API provides.

To enable debug, add this to your configuration.yaml and restart home assistant.

logger:
  default: info
  logs:
    custom_components.siemens_ozw672: debug

**Comment by MikaSeppala** [comment]
I can't restart home assistant as it gives an error: Invalid domain custom_components.siemens_ozw672

**Comment by johnaherninfotrack** [comment]
Sorry - the tabs got lost when I pasted.

`
logger:
  default: info
  logs:
    custom_components.siemens_ozw672: debug
`

**Comment by johnaherninfotrack** [comment]
Can not diagnose without debug
